/* Splits js/data.js (authoring source) into:
     js/data-core.js    — course structure, titles, durations, quiz questions
     js/data-content.js — lesson bodies + exercise starter/check (lazy-loaded)
   Run after every data.js edit:  node tools/split-data.js
   The app boots on core (fast) and pulls content when a lesson opens. */
const fs = require("fs");
const path = require("path");

global.window = {};
require(path.join(__dirname, "..", "js", "data.js"));
const { CATEGORIES, COURSES } = global.window.APP_DATA;

const content = {};
const core = COURSES.map((c) => Object.assign({}, c, {
  sections: c.sections.map((s) => ({
    title: s.title,
    lessons: s.lessons.map((l) => {
      const m = Object.assign({}, l);
      const bucket = {};
      if (m.content !== undefined) { bucket.c = m.content; delete m.content; }
      if (m.starter !== undefined) { bucket.s = m.starter; delete m.starter; }
      if (m.check !== undefined) { bucket.k = m.check; delete m.check; }
      if (Object.keys(bucket).length) content[l.id] = bucket;
      return m;
    }),
  })),
}));

const HEADER = "/* GENERATED by tools/split-data.js — edit js/data.js, then re-run. Do not edit by hand. */\n";
fs.writeFileSync(
  path.join(__dirname, "..", "js", "data-core.js"),
  HEADER + "window.APP_DATA = " + JSON.stringify({ CATEGORIES, COURSES: core }) + ";\n"
);
fs.writeFileSync(
  path.join(__dirname, "..", "js", "data-content.js"),
  HEADER + "window.APP_CONTENT = " + JSON.stringify(content) + ";\n"
);

const kb = (f) => Math.round(fs.statSync(path.join(__dirname, "..", "js", f)).size / 1024);
console.log("data-core.js:", kb("data-core.js") + " KB | data-content.js:", kb("data-content.js") + " KB | lessons with content:", Object.keys(content).length);
